"""imgs

Revision ID: 36e6fbf46755
Revises: 3cdf25d947a0
Create Date: 2023-11-16 22:50:57.290672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e6fbf46755'
down_revision = '3cdf25d947a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Content', schema=None) as batch_op:
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
