"""

Revision ID: 3cdf25d947a0
Revises: cbe73585d72b
Create Date: 2023-11-15 17:56:05.399931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cdf25d947a0'
down_revision = 'cbe73585d72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_content', sa.String(), nullable=True))
        batch_op.drop_constraint('Playlists_title_key', type_='unique')
        batch_op.create_foreign_key(None, 'Content', ['title_content'], ['title'])
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('Playlists_title_key', ['title'])
        batch_op.drop_column('title_content')

    # ### end Alembic commands ###
